### ISSUE TITLE
Multiple NPE when opening resource bundle files in Eclipse Neon

### ISSUE THREAD

**Issue by neo-de** [essiembre/eclipse-rbe#52]
RBE version 1.0.5

```
!ENTRY org.eclipse.ui.workbench 4 2 2016-06-29 09:22:39.649
!MESSAGE Problems occurred when invoking code from plug-in: "org.eclipse.ui.workbench".
!STACK 0
java.lang.NullPointerException
    at org.eclipse.wst.jsdt.chromium.debug.core.model.BreakpointAdapterFactory.getAdapter(BreakpointAdapterFactory.java:25)
    at org.eclipse.core.internal.adapter.AdapterFactoryProxy.getAdapter(AdapterFactoryProxy.java:82)
    at org.eclipse.core.internal.runtime.AdapterManager.getAdapter(AdapterManager.java:294)
    at org.eclipse.ui.part.WorkbenchPart.getAdapter(WorkbenchPart.java:143)
    at org.eclipse.ui.texteditor.AbstractTextEditor.getAdapter(AbstractTextEditor.java:6185)
    at com.essiembre.eclipse.rbe.ui.editor.i18n.I18nPageEditor.getAdapter(I18nPageEditor.java:90)
    at org.eclipse.core.runtime.Adapters.adapt(Adapters.java:59)
    at org.eclipse.core.runtime.Adapters.adapt(Adapters.java:100)
    at org.eclipse.ui.part.MultiPageEditorPart.getAdapter(MultiPageEditorPart.java:1199)
    at com.essiembre.eclipse.rbe.ui.editor.ResourceBundleEditor.getAdapter(ResourceBundleEditor.java:208)
    at org.eclipse.debug.internal.ui.actions.ToggleBreakpointsTargetManager$ToggleBreakpointsTargetAdapterFactory.canGetToggleBreakpointsTarget(ToggleBreakpointsTargetManager.java:318)
    at org.eclipse.debug.internal.ui.actions.ToggleBreakpointsTargetManager$ToggleBreakpointsTargetAdapterFactory.isEnabled(ToggleBreakpointsTargetManager.java:361)
    at org.eclipse.debug.internal.ui.actions.ToggleBreakpointsTargetManager.getEnabledFactories(ToggleBreakpointsTargetManager.java:502)
    at org.eclipse.debug.internal.ui.actions.ToggleBreakpointsTargetManager.getPreferredToggleBreakpointsTargetID(ToggleBreakpointsTargetManager.java:542)
    at org.eclipse.debug.internal.ui.actions.ToggleBreakpointsTargetManager.getToggleBreakpointsTarget(ToggleBreakpointsTargetManager.java:549)
    at org.eclipse.debug.internal.ui.actions.breakpoints.RetargetBreakpointAction.getAdapter(RetargetBreakpointAction.java:49)
    at org.eclipse.debug.internal.ui.actions.RetargetAction.partActivated(RetargetAction.java:169)
    at org.eclipse.ui.internal.PartService$1.run(PartService.java:84)
    at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
    at org.eclipse.ui.internal.PartService.partActivated(PartService.java:81)
    at org.eclipse.ui.internal.WorkbenchWindow$WWinPartService.partActivated(WorkbenchWindow.java:3002)
    at org.eclipse.ui.internal.WorkbenchPage$14.run(WorkbenchPage.java:4977)
    at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
    at org.eclipse.ui.internal.WorkbenchPage.firePartActivated(WorkbenchPage.java:4974)
    at org.eclipse.ui.internal.WorkbenchPage.access$19(WorkbenchPage.java:4962)
    at org.eclipse.ui.internal.WorkbenchPage$E4PartListener.partActivated(WorkbenchPage.java:210)
    at org.eclipse.e4.ui.internal.workbench.PartServiceImpl$3.run(PartServiceImpl.java:250)
    at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
    at org.eclipse.e4.ui.internal.workbench.PartServiceImpl.firePartActivated(PartServiceImpl.java:247)
    at org.eclipse.e4.ui.internal.workbench.PartServiceImpl.activate(PartServiceImpl.java:757)
    at org.eclipse.e4.ui.internal.workbench.PartServiceImpl.activate(PartServiceImpl.java:682)
    at org.eclipse.e4.ui.internal.workbench.PartServiceImpl.activate(PartServiceImpl.java:677)
    at org.eclipse.ui.internal.WorkbenchPage.busyOpenEditor(WorkbenchPage.java:3269)
    at org.eclipse.ui.internal.WorkbenchPage.access$25(WorkbenchPage.java:3176)
    at org.eclipse.ui.internal.WorkbenchPage$10.run(WorkbenchPage.java:3158)
    at org.eclipse.swt.custom.BusyIndicator.showWhile(BusyIndicator.java:70)
    at org.eclipse.ui.internal.WorkbenchPage.openEditor(WorkbenchPage.java:3153)
    at org.eclipse.ui.internal.WorkbenchPage.openEditor(WorkbenchPage.java:3117)
    at org.eclipse.ui.internal.WorkbenchPage.openEditor(WorkbenchPage.java:3107)
    at org.eclipse.ui.ide.IDE.openEditor(IDE.java:563)
    at org.eclipse.ui.ide.IDE.openEditor(IDE.java:518)
    at org.eclipse.jdt.internal.ui.javaeditor.EditorUtility.openInEditor(EditorUtility.java:360)
    at org.eclipse.jdt.internal.ui.javaeditor.EditorUtility.openInEditor(EditorUtility.java:167)
    at org.eclipse.jdt.ui.actions.OpenAction.run(OpenAction.java:256)
    at org.eclipse.jdt.ui.actions.OpenAction.run(OpenAction.java:221)
    at org.eclipse.jdt.ui.actions.SelectionDispatchAction.dispatchRun(SelectionDispatchAction.java:271)
    at org.eclipse.jdt.ui.actions.SelectionDispatchAction.run(SelectionDispatchAction.java:249)
    at org.eclipse.jdt.internal.ui.packageview.PackageExplorerActionGroup.handleOpen(PackageExplorerActionGroup.java:379)
    at org.eclipse.jdt.internal.ui.packageview.PackageExplorerPart$4.open(PackageExplorerPart.java:540)
    at org.eclipse.ui.OpenAndLinkWithEditorHelper$InternalListener.open(OpenAndLinkWithEditorHelper.java:46)
    at org.eclipse.jface.viewers.StructuredViewer$2.run(StructuredViewer.java:855)
    at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
    at org.eclipse.ui.internal.JFaceUtil$1.run(JFaceUtil.java:50)
    at org.eclipse.jface.util.SafeRunnable.run(SafeRunnable.java:173)
    at org.eclipse.jface.viewers.StructuredViewer.fireOpen(StructuredViewer.java:852)
    at org.eclipse.jface.viewers.StructuredViewer.handleOpen(StructuredViewer.java:1169)
    at org.eclipse.jface.util.OpenStrategy.fireOpenEvent(OpenStrategy.java:278)
    at org.eclipse.jface.util.OpenStrategy.access$2(OpenStrategy.java:272)
    at org.eclipse.jface.util.OpenStrategy$1.handleEvent(OpenStrategy.java:313)
    at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:84)
    at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4410)
    at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1079)
    at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4228)
    at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3816)
    at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$4.run(PartRenderingEngine.java:1121)
    at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336)
    at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1022)
    at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:150)
    at org.eclipse.ui.internal.Workbench$5.run(Workbench.java:687)
    at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336)
    at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:604)
    at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:148)
    at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:138)
    at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
    at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
    at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
    at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:388)
    at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:243)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:673)
    at org.eclipse.equinox.launcher.Main.basicRun(Main.java:610)
    at org.eclipse.equinox.launcher.Main.run(Main.java:1519)
```

**Comment by thimo-seitz** [comment]
Hello,
As a workaround you could deinstall the Plugin "JavaScript Development Tools Chromium/V8 Remote Debugger" in the case you do not use that.

Best Regards

**Comment by thimo-seitz** [comment]
Seems to be a missing NP-Check in the jsdt-project. Is also reported as a bug there: https://bugs.eclipse.org/bugs/show_bug.cgi?id=496914

**Comment by chrisvoo** [comment]
Hi @thimo-seitz,
unfortunately it seems that uninstalling the plugin you said only solves NPE to pop out, but the right UI for editing properties did not come out. Only the tree on the left for navigating through properties seems to work.

**Comment by thimo-seitz** [comment]
Hi @chrisvoo,
the rbe is usable in my installation with or without the V8-Debugger-Plugin as usual, apart from the NPEs. Even with the other plugin installed i can edit. Maybe you're using an other version of rbe? I've installed 1.0.5.
Best Regards

![unbenannt](https://cloud.githubusercontent.com/assets/20231368/16723903/11c8cd60-4750-11e6-8466-2410fad44ff6.png)

**Comment by chrisvoo** [comment]
@thimo-seitz I'm using  ResourceBundle Editor 1.0.56 and I've noticed there was already an issue #50

**Comment by icecuber** [comment]
Using 1.05 version on Neon, got this problem too :(

**Comment by fsilkswan** [comment]
Is there a way to suppress the NPE in Eclipse Neon without losing RBE functionality?

**Comment by icecuber** [comment]
I have a 'better' workaround.. at least for me! i got RBE working correctly in a clean **Java Neon** Install, seems that the **Jee flavour** force you to have the offending V8-Debugger-Plugin installed...

**Comment by mpscheidt** [comment]
To get rid of the NPEs in Spring Tool Suite 3.8.2, I had to remove the JSDT Chromium Debugger, more specifically, remove the files org.eclipse.wst.jsdt.chromium.debug.* from the Eclipse plugins directory.

**Comment by noemus** [comment]
I have solved this problem by patching the org.eclipse.wst.jsdt.chromium.debug.core.model.BreakpointAdapterFactory class
There should be null check after calling the getEditorInput() method. Original code is: 
... editorPart.getEditorInput().getAdapter() ...
 But in RBE editorPart.getEditorInput() returns null

Here is modified jar file - I will try to contact authors.
[org.eclipse.wst.jsdt.chromium.debug.core_0.5.0.v201608251013.jar.zip](https://github.com/essiembre/eclipse-rbe/files/541448/org.eclipse.wst.jsdt.chromium.debug.core_0.5.0.v201608251013.jar.zip)

But there is even more severe problem in class org.eclipse.core.internal.runtime.AdapterManager (getAdapter() method) in equinox runtime. This class calls factories from various plugins and there is no try catch to handle errors in these external plugins. So for now problem is solved, but it will occur againt in another plugin. So better choice is to modify AdapterManager class so it will handle appropriatelly errors in plugins. This very, very long story.

**Comment by de-jcup** [comment]
The bug is fixed now in master, (see https://bugs.eclipse.org/bugs/show_bug.cgi?id=496914 ).

But the described workaround of "...deinstall the Plugin "JavaScript Development Tools Chromium/V8 Remote Debugger" ..." does sorrowly not work, because the remote debugger plugin is still active, even after deinstallation - see https://bugs.eclipse.org/bugs/show_bug.cgi?id=506605

**Comment by joergrech** [comment]
How can I get the fix/master? I downloaded Neon.2 (4.6.2) with JavaScript Development Tools	2.0.0.v201608301904 and have RBE 1.0.5 but the NPEs are still coming :-( 

Is there a special update site?

**Comment by de-jcup** [comment]
As mentioned in1https://bugs.eclipse.org/bugs/show_bug.cgi?id=496914 the target milestone is 3.8.2 . I am using neon.2 too but installed is currently 3.8.0 /3.8.1 parts

![image](https://cloud.githubusercontent.com/assets/11644753/21913939/30f59a98-d930-11e6-87df-ccdb1d7c0e87.png)

I also still got the problems with NPE - I think the 3.8.2 release will come in next time by a "check for updates".

**Comment by essiembre** [comment]
1.0.6 now addresses by logging the exception instead.  Please confirm.

**Comment by tanrikut** [comment]
I updated to 1.0.6 and although NPE disappeared, right panel is empty and following exception is logged:
(Neon.2 and RBE 1.0.6)
```
Exception:org.eclipse.swt.SWTException: Widget is disposed
	 at org.eclipse.swt.SWT.error(SWT.java:4533)
	 at org.eclipse.swt.SWT.error(SWT.java:4448)
	 at org.eclipse.swt.SWT.error(SWT.java:4419)
	 at org.eclipse.swt.widgets.Widget.error(Widget.java:482)
	 at org.eclipse.swt.widgets.Widget.checkWidget(Widget.java:354)
	 at org.eclipse.swt.widgets.Control.getSize(Control.java:1607)
	 at org.eclipse.swt.widgets.ScrollBarAdapter.getSize(ScrollBarAdapter.java:57)
	 at org.eclipse.swt.custom.ScrolledCompositeLayout.layout(ScrolledCompositeLayout.java:65)
	 at org.eclipse.swt.widgets.Composite.updateLayout(Composite.java:1386)
	 at org.eclipse.swt.widgets.Composite.sendResize(Composite.java:1062)
	 at org.eclipse.swt.widgets.Composite.setBoundsInPixels(Composite.java:1108)
	 at org.eclipse.swt.widgets.Control.setBoundsInPixels(Control.java:3220)
	 at org.eclipse.swt.widgets.Control.setBoundsInPixels(Control.java:3216)
	 at org.eclipse.swt.widgets.Control.setBounds(Control.java:3211)
	 at org.eclipse.swt.custom.SashFormLayout.layout(SashFormLayout.java:172)
	 at org.eclipse.swt.widgets.Composite.updateLayout(Composite.java:1386)
	 at org.eclipse.swt.widgets.Composite.WM_SIZE(Composite.java:1797)
	 at org.eclipse.swt.widgets.Control.windowProc(Control.java:4874)
	 at org.eclipse.swt.widgets.Display.windowProc(Display.java:5110)
	 at org.eclipse.swt.internal.win32.OS.DefWindowProcW(OS.java:-2)
	 at org.eclipse.swt.internal.win32.OS.DefWindowProc(OS.java:2547)
	 at org.eclipse.swt.widgets.Scrollable.callWindowProc(Scrollable.java:88)
	 at org.eclipse.swt.widgets.Control.WM_WINDOWPOSCHANGED(Control.java:5699)
	 at org.eclipse.swt.widgets.Control.windowProc(Control.java:4887)
	 at org.eclipse.swt.widgets.Display.windowProc(Display.java:5110)
	 at org.eclipse.swt.internal.win32.OS.SetWindowPos(OS.java:-2)
	 at org.eclipse.swt.widgets.Widget.SetWindowPos(Widget.java:1482)
	 at org.eclipse.swt.widgets.Control.setBoundsInPixels(Control.java:3259)
	 at org.eclipse.swt.widgets.Composite.setBoundsInPixels(Composite.java:1102)
	 at org.eclipse.swt.widgets.Control.setBoundsInPixels(Control.java:3220)
	 at org.eclipse.swt.widgets.Control.setBoundsInPixels(Control.java:3216)
	 at org.eclipse.swt.widgets.Control.setBoundsInPixels(Control.java:3292)
	 at org.eclipse.swt.widgets.Control.setBounds(Control.java:3288)
	 at org.eclipse.swt.custom.ScrolledCompositeLayout.layout(ScrolledCompositeLayout.java:134)
	 at org.eclipse.swt.widgets.Composite.updateLayout(Composite.java:1386)
	 at org.eclipse.swt.widgets.Composite.WM_SIZE(Composite.java:1797)
	 at org.eclipse.swt.widgets.Control.windowProc(Control.java:4874)
	 at org.eclipse.swt.widgets.Display.windowProc(Display.java:5110)
	 at org.eclipse.swt.internal.win32.OS.DefWindowProcW(OS.java:-2)
	 at org.eclipse.swt.internal.win32.OS.DefWindowProc(OS.java:2547)
	 at org.eclipse.swt.widgets.Scrollable.callWindowProc(Scrollable.java:88)
	 at org.eclipse.swt.widgets.Control.WM_WINDOWPOSCHANGED(Control.java:5699)
	 at org.eclipse.swt.widgets.Control.windowProc(Control.java:4887)
	 at org.eclipse.swt.widgets.Display.windowProc(Display.java:5110)
	 at org.eclipse.swt.internal.win32.OS.SetWindowPos(OS.java:-2)
	 at org.eclipse.swt.widgets.Widget.SetWindowPos(Widget.java:1482)
	 at org.eclipse.swt.widgets.Control.setBoundsInPixels(Control.java:3259)
	 at org.eclipse.swt.widgets.Composite.setBoundsInPixels(Composite.java:1102)
	 at org.eclipse.swt.widgets.Control.setBoundsInPixels(Control.java:3220)
	 at org.eclipse.swt.widgets.Control.setBoundsInPixels(Control.java:3216)
	 at org.eclipse.swt.widgets.Control.setBounds(Control.java:3211)
	 at org.eclipse.swt.layout.FillLayout.layout(FillLayout.java:204)
	 at org.eclipse.swt.widgets.Composite.updateLayout(Composite.java:1386)
	 at org.eclipse.swt.widgets.Composite.WM_SIZE(Composite.java:1797)
	 at org.eclipse.swt.widgets.Control.windowProc(Control.java:4874)
	 at org.eclipse.swt.widgets.Display.windowProc(Display.java:5110)
	 at org.eclipse.swt.internal.win32.OS.DefWindowProcW(OS.java:-2)
	 at org.eclipse.swt.internal.win32.OS.DefWindowProc(OS.java:2547)
	 at org.eclipse.swt.widgets.Scrollable.callWindowProc(Scrollable.java:88)
	 at org.eclipse.swt.widgets.Control.WM_WINDOWPOSCHANGED(Control.java:5699)
	 at org.eclipse.swt.widgets.Control.windowProc(Control.java:4887)
	 at org.eclipse.swt.widgets.Display.windowProc(Display.java:5110)
	 at org.eclipse.swt.internal.win32.OS.EndDeferWindowPos(OS.java:-2)
	 at org.eclipse.swt.widgets.Composite.resizeChildren(Composite.java:1030)
	 at org.eclipse.swt.widgets.Composite.resizeChildren(Composite.java:996)
	 at org.eclipse.swt.widgets.Composite.setResizeChildren(Composite.java:1210)
	 at org.eclipse.swt.widgets.Composite.WM_SIZE(Composite.java:1801)
	 at org.eclipse.swt.widgets.Control.windowProc(Control.java:4874)
	 at org.eclipse.swt.widgets.Display.windowProc(Display.java:5110)
	 at org.eclipse.swt.internal.win32.OS.DefWindowProcW(OS.java:-2)
	 at org.eclipse.swt.internal.win32.OS.DefWindowProc(OS.java:2547)
	 at org.eclipse.swt.widgets.Scrollable.callWindowProc(Scrollable.java:88)
	 at org.eclipse.swt.widgets.Control.WM_WINDOWPOSCHANGED(Control.java:5699)
	 at org.eclipse.swt.widgets.Control.windowProc(Control.java:4887)
	 at org.eclipse.swt.widgets.Display.windowProc(Display.java:5110)
	 at org.eclipse.swt.internal.win32.OS.SetWindowPos(OS.java:-2)
	 at org.eclipse.swt.widgets.Widget.SetWindowPos(Widget.java:1482)
	 at org.eclipse.swt.widgets.Control.setBoundsInPixels(Control.java:3259)
	 at org.eclipse.swt.widgets.Composite.setBoundsInPixels(Composite.java:1102)
	 at org.eclipse.swt.widgets.Control.setBoundsInPixels(Control.java:3220)
	 at org.eclipse.swt.widgets.Control.setBoundsInPixels(Control.java:3216)
	 at org.eclipse.swt.widgets.Control.setBounds(Control.java:3211)
	 at org.eclipse.swt.layout.FillLayout.layout(FillLayout.java:204)
	 at org.eclipse.swt.widgets.Composite.updateLayout(Composite.java:1386)
	 at org.eclipse.swt.widgets.Composite.WM_SIZE(Composite.java:1797)
	 at org.eclipse.swt.widgets.Control.windowProc(Control.java:4874)
	 at org.eclipse.swt.widgets.Display.windowProc(Display.java:5110)
	 at org.eclipse.swt.internal.win32.OS.DefWindowProcW(OS.java:-2)
	 at org.eclipse.swt.internal.win32.OS.DefWindowProc(OS.java:2547)
	 at org.eclipse.swt.widgets.Scrollable.callWindowProc(Scrollable.java:88)
	 at org.eclipse.swt.widgets.Control.WM_WINDOWPOSCHANGED(Control.java:5699)
	 at org.eclipse.swt.widgets.Control.windowProc(Control.java:4887)
	 at org.eclipse.swt.widgets.Display.windowProc(Display.java:5110)
	 at org.eclipse.swt.internal.win32.OS.SetWindowPos(OS.java:-2)
	 at org.eclipse.swt.widgets.Widget.SetWindowPos(Widget.java:1482)
	 at org.eclipse.swt.widgets.Control.setBoundsInPixels(Control.java:3259)
	 at org.eclipse.swt.widgets.Composite.setBoundsInPixels(Composite.java:1102)
	 at org.eclipse.swt.widgets.Control.setBoundsInPixels(Control.java:3220)
	 at org.eclipse.swt.widgets.Control.setBoundsInPixels(Control.java:3216)
	 at org.eclipse.swt.widgets.Control.setBounds(Control.java:3211)
	 at org.eclipse.swt.layout.FillLayout.layout(FillLayout.java:219)
	 at org.eclipse.swt.widgets.Composite.updateLayout(Composite.java:1386)
	 at org.eclipse.swt.widgets.Composite.updateLayout(Composite.java:1393)
	 at org.eclipse.swt.widgets.Composite.updateLayout(Composite.java:1393)
	 at org.eclipse.swt.widgets.Composite.updateLayout(Composite.java:1393)
	 at org.eclipse.swt.widgets.Composite.updateLayout(Composite.java:1393)
	 at org.eclipse.swt.widgets.Composite.updateLayout(Composite.java:1393)
	 at org.eclipse.swt.widgets.Composite.updateLayout(Composite.java:1393)
	 at org.eclipse.swt.widgets.Composite.updateLayout(Composite.java:1393)
	 at org.eclipse.swt.widgets.Composite.updateLayout(Composite.java:1393)
	 at org.eclipse.swt.widgets.Composite.updateLayout(Composite.java:1393)
	 at org.eclipse.swt.widgets.Composite.updateLayout(Composite.java:1371)
	 at org.eclipse.swt.widgets.Composite.setLayoutDeferred(Composite.java:1170)
	 at org.eclipse.swt.widgets.Display.runDeferredLayouts(Display.java:4260)
	 at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3817)
	 at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$4.run(PartRenderingEngine.java:1121)
	 at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336)
	 at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1022)
	 at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:150)
	 at org.eclipse.ui.internal.Workbench$5.run(Workbench.java:693)
	 at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336)
	 at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:610)
	 at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:148)
	 at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:138)
	 at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
	 at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
	 at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	 at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:388)
	 at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:243)
	 at sun.reflect.NativeMethodAccessorImpl.invoke0(null:-2)
	 at sun.reflect.NativeMethodAccessorImpl.invoke(null:-1)
	 at sun.reflect.DelegatingMethodAccessorImpl.invoke(null:-1)
	 at java.lang.reflect.Method.invoke(null:-1)
	 at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:673)
	 at org.eclipse.equinox.launcher.Main.basicRun(Main.java:610)
	 at org.eclipse.equinox.launcher.Main.run(Main.java:1519)
	 at org.eclipse.equinox.launcher.Main.main(Main.java:1492)
```

**Comment by essiembre** [comment]
I am using the same version and I cannot reproduce.  Do you have specific steps to reproduce?  The stacktrace you provided does not reference the eclipse-rbe plugin so it is hard to tell what might be causing this.

**Comment by tanrikut** [comment]
Because I am getting NPEs, I have updated from 1.0.5 to 1.0.6 using update site. Than I opened a .properties file with RBE. When I select a key from left panel nothing is show at right panel. I have two properties files for default and tr_TR languages. When I click on an item at left panel, I got this exception logged at Eclipse Error Log. 

I know it is not so much information, but this is what I can tell for now.

**Comment by de-jcup** [comment]
Hello @essiembre , I tried out your Version 1.0.6 with eclipse neon.2 and it works well. No longer anoying popup coming up with NPE messages, instead all errors are directed to log:

![image](https://cloud.githubusercontent.com/assets/11644753/23358448/42a1462c-fce2-11e6-8ef0-4a2738ec0077.png)

Thank you :-) 

By the way: Eclipse market place still shows version 1.0.5. Maybe you forgot to update the site description?

Last but not least: **just a suggestion:**
Maybe it would be a good idea  - as long as the bug exists in web tools plugins - to check for these 2 dedicated NPEs. and only **log one time** eclipse is started. So the error would be logged, but only one time, and would no longer fill the error logs. 

I think this could be done by integrating field(s) in Activator class to hold information about logged NPEs:
ala `boolean alreadyLoggedNPEFromJavaWebDeveloperTools;` and to check before doing the log (+ setting flag...)

**Comment by neo-de** [comment]
Version 1.0.6 also fixes the problem for me.

**Comment by fsilkswan** [comment]
Thanks for the fix! :)
